name: Donnation
description: Mon premier projet Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/LOGO2.png
    - assets/donate.png
    - assets/request.png
    - assets/slider1.png
    - assets/sara.png
    - assets/amine.png
    - assets/mohamed.png

