name: Donnation
description: Mon premier projet Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.2
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  sqflite: ^2.4.2
  path: ^1.9.1

  mailer: ^6.6.0

  firebase_core: ^3.7.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/LOGO2.png
    - assets/donate.png
    - assets/request.png
    - assets/slider1.png
    - assets/sara.png
    - assets/amine.png
    - assets/mohamed.png
    - assets/profile.png
    - assets/ramy.png
    - assets/yucef.png
